### ISSUE TITLE
make like llama2.c

### ISSUE THREAD

**Issue by emma-eva** [Eliyaan/preceptron_v_module#1]
would be great if you can do like this: https://github.com/karpathy/llama2.c

thanks in advance

**Comment by Eliyaan** [comment]
Hello, I'll take a look into that. But I'm not sure that I understand exactly what you want (if it's easier for you we can talk about it on discord I'll answer faster, my tag is nopana).

**Comment by emma-eva** [comment]
its chatgpt like, gpt2 features. they trained story at this time. convert c to v that project.

**Comment by emma-eva** [comment]
v have not buffer reader like go and c. for that i failed to made it using vlang.

**Comment by Eliyaan** [comment]
> its chatgpt like, gpt2 features. they trained story at this time. convert c to v that project.

Hm tell me if I'm wrong, but this has nothing to do with this project,  so I dont know why you ask me to do it.
